name: Push to AWS ECR & deploy

on:
  push:
    branches:
      - master  # Adjust branch as needed

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          ecr-repo: ${{ secrets.ECR_REPO }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 # Adjust region as needed

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin $ecr-repo

      - name: Build, Tag, and Push Docker Image
        env:
          ECR_REPOSITORY: $ecr-repo
          IMAGE_TAG: latest  # Change the tag if needed
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
